### ISSUE TITLE
Crash while syncing

### ISSUE THREAD

**Issue by AlexeyAkhunov** [umbracle/minimal#108]
Sometimes during synching to mainnet, minimal crashes with this stack trace:
```
SYNC RECEIPTS (7992fa8471ae906764a6069f98696e767e63aef6b7e8dba6788ae01426ee8e48adb74c2a3db39e51677ab9384ac835e17c49965ac615fdb85e2d39345da4eec6): 72
deliver headers 526: 190
SYNC HEADERS (31bf0e6c8e717affe5970f8c65f53da5225162c5a65f0b0f8f5e227f96f740639878e1660eae37e444f26d8812b3d4e5fec94d9b6dbfba2efffb1891cc8bd7cc): 103361 190
SYNC BODIES (7992fa8471ae906764a6069f98696e767e63aef6b7e8dba6788ae01426ee8e48adb74c2a3db39e51677ab9384ac835e17c49965ac615fdb85e2d39345da4eec6): 79
deliver headers 527: 190
panic: runtime error: index out of range

goroutine 43211 [running]:
github.com/umbracle/minimal/protocol/ethereum.workersHeapImpl.Swap(...)
	/Users/alexeyakhunov/workspace/src/github.com/umbracle/minimal/protocol/ethereum/backend.go:620
container/heap.Remove(0x4bd7060, 0xc000336ec8, 0xffffffffffffffff, 0x80, 0xc0007b68c0)
	/usr/local/Cellar/go/1.12/libexec/src/container/heap/heap.go:72 +0x9c
github.com/umbracle/minimal/protocol/ethereum.(*workersHeap).Remove(0xc000336ec0, 0xc009b810e2, 0x80)
	/Users/alexeyakhunov/workspace/src/github.com/umbracle/minimal/protocol/ethereum/backend.go:571 +0x88
github.com/umbracle/minimal/protocol/ethereum.(*Backend).runTask(0xc0000ea840, 0xc00ac16480)
	/Users/alexeyakhunov/workspace/src/github.com/umbracle/minimal/protocol/ethereum/backend.go:179 +0x5f
created by github.com/umbracle/minimal/protocol/ethereum.(*Backend).runSync
	/Users/alexeyakhunov/workspace/src/github.com/umbracle/minimal/protocol/ethereum/backend.go:252 +0x5d
exit status 2
```

**Comment by ferranbt** [comment]
Could you check if this fix works? Thx!
https://github.com/umbracle/minimal/tree/fix/eth63-workpool-crash
