### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by igorbarinov** [umbracle/minimal#82]
When I run master from my local comupter (Mac) using `go run main.go agent` command I got 

```
-- addr --
127.0.0.1
30303
Enode: enode://939adec24cbf8102eaf2fdc09574aac3d1cb4e1cc192b0e3d0445ffecaf4a8fa9cc00bf4bc6af17d3b27ae746933606923ab081b5b42d45a03a8ffc56d01327c@127.0.0.1:30303
Current header (0): 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x457e11d]

goroutine 1 [running]:
github.com/umbracle/minimal/network.(*Server).Schedule(0xc0008be1c0, 0x508a598, 0x0)
	/Users/user/g/minimal/network/server.go:185 +0x13d
github.com/umbracle/minimal/minimal.NewMinimal(0xc0008a0550, 0xc0008a2aa0, 0x2, 0xc0002ea4f0, 0xe)
	/Users/user/g/minimal/minimal/minimal.go:195 +0x1a18
github.com/umbracle/minimal/command/agent.(*Agent).Start(0xc0000c3620, 0xc0000c3620, 0x0)
	/Users/user/g/minimal/command/agent/agent.go:147 +0x851
github.com/umbracle/minimal/command/agent.(*AgentCommand).Run(0xc0000c58d0, 0xc0000c2010, 0x0, 0x0, 0xc0000c58a0)
	/Users/user/g/minimal/command/agent/command.go:96 +0x1b1
github.com/mitchellh/cli.(*CLI).Run(0xc0001288c0, 0xc0001288c0, 0xc0000fd530, 0xc0001fdf58)
	/Users/user/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.Run(0xc0000c2010, 0x1, 0x1, 0xc000092058)
	/Users/user/g/minimal/main.go:24 +0xa3
main.main()
	/Users/user/g/minimal/main.go:12 +0x62
exit status 2
➜  minimal git:(master) ✗
```

go version go1.12.4 darwin/amd64

**Comment by ferranbt** [comment]
Thank you for opening the first issue!
I was aware of it. It is related to some refactoring I did a couple of weeks ago. It should be fixed in the following days alongside an update in the README with information on how to configure the client.

**Comment by ferranbt** [comment]
The issue has been fixed now in the branch develop. Note that you may still find some panics placed intentionally in areas where the logic is still not defined or unknown. Anyway, please open another issue if you come across any other error.
